### ISSUE TITLE
breaking change 0.4.5 to 0.4.7

### ISSUE THREAD

**Issue by Safari77** [MIERUNE/earcut-rs#27]
0.4.7:
```
error[E0277]: the trait bound `T: AsPrimitive<u32>` is not satisfied
   --> /home/safari/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/geo-0.33.0/src/algorithm/triangulate_earcut.rs:131:16
    |
131 |         earcut.earcut(
    |                ^^^^^^ the trait `AsPrimitive<u32>` is not implemented for `T`
    |
note: required by a bound in `Earcut::<T>::earcut`
   --> /home/safari/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/earcut-0.4.7/src/lib.rs:167:17
    |
167 | impl<T: Float + AsPrimitive<u32>> Earcut<T> {
    |                 ^^^^^^^^^^^^^^^^ required by this bound in `Earcut::<T>::earcut`
...
```

Works if I do
```bash
$ cargo update -p earcut --precise 0.4.5 --verbose
```

**Comment by michaelkirk** [comment]
It looks like breaking changes were introduced in https://github.com/ciscorn/earcut-rs/pull/26

Because you added a new trait constraint, you should have made a "breaking" (in the semver sense) release. Instead you made a patch release [which has broken things](https://github.com/georust/geo/issues/1526). 

My advice: You should revert the semver breaking changes, publish it as 0.4.8, then re-publish your breaking changes as 0.5.0

**Comment by ciscorn** [comment]
Sorry for the trouble. I've released 0.4.8 with the same contents as 0.4.5, and yanked 0.4.7. I'll publish the breaking changes as 0.5.0 separately.

**Comment by michaelkirk** [comment]
Thank you! Looking forward to the additional performance in 0.5!

**Comment by ciscorn** [comment]
I took another look, and the benefit of the `AsPrimitive<u32>` trait bound does not seem to outweigh the usability cost. So I'm planning to remove it and make the next release non-breaking instead.
